### ISSUE TITLE
Doesn't work on vivaldi

### ISSUE THREAD

**Issue by burgyman** [jadeohl/linkmd#1]
Works well on Chrome, but it's a pity it doesn't work on Vivaldi (my daily driver). Please have a look and fix it.

**Comment by jadeohl** [comment]
@burgyman I replicated the problem in Vivaldi and have new version which is working for me now in Vivaldi. Once 1.1 is approved in the Chrome Web Store please try it.

**Comment by burgyman** [comment]
Thanks for fixing the issue with version 1.1
The only thing I still can't get to work is the shortcut key. Please check it.

**Comment by jadeohl** [comment]
Unfortunately it looks like extension hotkeys not working is a known issue with Vivaldi. In the Vivaldi internal bug tracking it is VB-14668.

There are multiple threads on this, but this seems to be the best one: https://forum.vivaldi.net/topic/31027/keyboard-shortcuts-not-working-with-extensions/43?lang=en-US&page=3 You can see as of 18 days ago the complaint of it being a bug for 3 years. Someone at least does say "VB-14668 has gotten renewed attention in the past few weeks"
